# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00f91310f2eff278f5cfebcc9dde232396e95fdc6f3b9c71947adcb1b96b3acf54caaee55cbc36085028e5c259ec0d4b5021ed620e15322a1eae0657058fccfe

test:
  secret_key_base: eb5f53098aea2139ea197fbc66ca6c05cf44f9233da75484c9fb06f126dd3c9c9f1e34bdb0d555dcffc82ef3c6cc510b07946e463afe20e76527a26147218344

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
